# Clase 1 - Ejemplos prácticos
## Colab
Google Colab es un servicio en la nube gratuito que permite escribir y ejecutar código Python en el navegador, sin necesidad de configuración. Funciona como un entorno de trabajo colaborativo similar a los Jupyter Notebooks, pero alojado en los servidores de Google, lo que facilita el acceso a recursos de computación como GPUs y TPUs para tareas como aprendizaje automático y análisis de datos.

Colab posee lo que son celdas de texto y celdas de código. En las celdas de texto como esta se utiliza Markdown para dar formato al texto. A continuación algunos, ejemplos:

*texto en cursiva*

**texto en negrita**



```
# Tiene formato de código
```

[texto del enlace](https://)



Las celdas de código permiten ejecutar código python. Y muestran la salida en la parte inferiror de cada una.

In [ ]:
saludo = 'Hola mundo'

print(saludo)

Hola mundo


En una celda de código es posible imprimir la variable simplemente escribirndo el nombre de la misma.

In [ ]:
saludo

'Hola mundo'

Las variables y funciones que pertenecen al entorno global pueden ser utilizadas en cualquier parte del notebook.

## Instalación de librerías

In [ ]:
!pip install tensorflow #Debe anteponerse el signo ! para realizar una instalación en colab

# Numpy
NumPy es una biblioteca de Python que facilita la computación científica, la manipulación de datos y cálculos numéricos. Su nombre proviene de "Numerical Python" y proporciona soporte para trabajar con arreglos y matrices multidimensionales de alto rendimiento, junto con una amplia colección de funciones matemáticas de alto nivel para operar con ellos.

Algunas de las funciones más comunes son:

* np.array([1, 2, 3]) — crea un array
* np.zeros((3,3)) — crea una matriz de ceros de 3x3
* np.mean(array) — promedio de elementos
* np.dot(A, B) — producto punto de matrices A y B

### Creación de Arrays

In [3]:
import numpy as np

a = [1,2,3,4,5,6,7]
print(a)

print('-'*15)
b = np.array(a)
b

[1, 2, 3, 4, 5, 6, 7]
---------------


array([1, 2, 3, 4, 5, 6, 7])

### Creación de una matriz de ceros

In [ ]:
c = np.zeros((4,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Calcular la media

In [ ]:
media = np.mean(b)
media

np.float64(4.0)

### Operaciones matemáticas con arrays

In [4]:
# suma
d = np.array([2,4,6,8,10,12,14])

b+d

array([ 3,  6,  9, 12, 15, 18, 21])

In [5]:
# resta
d-b

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# multiplicación
b*d

array([ 2,  8, 18, 32, 50, 72, 98])

In [ ]:
# división
d/b

array([2., 2., 2., 2., 2., 2., 2.])

In [ ]:
# multiplicación por un escalar
d*5

array([10, 20, 30, 40, 50, 60, 70])

In [ ]:
# producto punto
np.dot(b, d)

np.int64(280)

### Crear una matriz de unos

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Crear un arreglo de numeros especificando el inicio, final y el paso

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### Crear un arreglo de números equidistantes

In [ ]:
np.linspace(0,2, 4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

### Crear una matriz identidad

In [ ]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Crear un arreglo de numeros aleatorios

In [7]:
random = np.random.rand(0,10)
random

array([], shape=(0, 10, 2), dtype=float64)

### Indexación

In [ ]:
b[0]

np.int64(1)

In [ ]:
e[0][2]

np.float64(0.0)

In [ ]:
e[0,2]

np.float64(0.0)

In [ ]:
b[1:4]

array([2, 3, 4])

### Conocer las dimensiones de un arreglo

In [ ]:
b.shape

(7,)

In [ ]:
e.shape

(3, 3)

### Otras funciones

In [ ]:
print('Suma', np.sum(b))

Suma 28


In [ ]:
np.max(b)

np.int64(7)

In [ ]:
# Crear matriz con valores aleatorios
matriz = np.random.randint(1, 20, (4,3))
matriz

array([[10,  9,  9],
       [14, 11, 13],
       [ 5,  5, 10],
       [18, 12,  6]])

In [ ]:
np.mean(matriz, axis=0)

array([11.75,  9.25,  9.5 ])

# Pandas

## Serie

In [ ]:
import pandas as pd

serie = pd.Series([10,15,14,17], index=['a', 'b', 'c', 'd'])
serie

a    10
b    15
c    14
d    17
dtype: int64

In [ ]:
diccionario = {'Maria': 20, 'Mario': 14, 'Jose': 12}
serie2 = pd.Series(diccionario)
serie2

Maria    20
Mario    14
Jose     12
dtype: int64

In [ ]:
serie3 = pd.Series(b)
serie3

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64